catalogs:
  - name: gold01
    ref: catalog001
    metastore_type: unity
    catalog_name: gold01
    credential: sc_framework
    uri: https://gold1dev.dfs.core.windows.net/
    class: gold
    schemas:
      - name: finanzas
        ref: finanzas001
        uri: finanzas/
      - name: ventas
        ref: ventas001
        uri: ventas/

  - name: silver01
    ref: catalog002
    metastore_type: unity
    catalog_name: silver01
    credential: sc_framework
    uri: https://gold1dev.dfs.core.windows.net/
    class: silver
    schemas:
      - name: finanzas
        ref: finanzas001
        uri: finanzas/
      - name: ventas
        ref: ventas001
        uri: ventas/

  - name: bronze01
    ref: catalog003
    metastore_type: unity
    catalog_name: bronze01
    credential: sc_framework
    uri: https://gold1dev.dfs.core.windows.net/
    class: bronze
    schemas:
      - name: finanzas
        ref: finanzas001
        uri: finanzas/
      - name: ventas
        ref: ventas001
        uri: ventas/

credentials:
  - name: sc_framework
    ref: sc_framework
    cloud: azure
    auth_type: managed_identity
    access_connector_id: /subscriptions/98671ec6-27f7-46d9-8dfd-9ff32cc57480/resourceGroups/rg-microsoft/providers/Microsoft.Databricks/accessConnectors/framework
    user_assigned_identity_id: "/subscriptions/xxxx/resourceGroups/rg-dbx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ua-dev-mi"
    comment: "Credencial framework DEV"
    read_only: false
	

